### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by mkeresty** [MetaMask/extension-provider#29]
im getting: 

Uncaught ReferenceError: process is not defined
    at 9306 (index.js:6:29)
    at r (bootstrap:19:32)
    at 3530 (BaseProvider.ts:2:1)
    at r (bootstrap:19:32)
    at 5361 (MetaMaskInpageProvider.ts:7:1)
    at r (bootstrap:19:32)
    at 9955 (index.ts:1:1)
    at r (bootstrap:19:32)
    at 4653 (index.js:1:36)
    at r (bootstrap:19:32)

ive tried:
- manifest v2 & v3
- installing stream and stream-browserify and adding them as fallbacks

**Comment by kesar** [comment]
getting same error +1

**Comment by mkeresty** [comment]
@kesar i found a way around this. Use walletconnect v1

**Comment by zouhangwithsweet** [comment]
I build a strong webext-dapp-template: https://github.com/fisand/webext-dapp-template.
