### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/extension-provider#48]
```
ReferenceError: process is not defined
  at Readable.pipe (_stream_readable.js:581:1)
  at pipe (index.js:56:1)
  at Array.reduce (<anonymous>)
  at Object.pump [as default] (index.js:79:1)
  at new BaseProvider (BaseProvider.js:49:1)
  at new MetaMaskInpageProvider (MetaMaskInpageProvider.js:24:1)
  at createMetaMaskProvider (index.js:13:1)
```

**Comment by Jack-Works** [comment]
Yes. This package relies on `extension-port-stream` and it relies on `readable-stream`. Three accesses to `process` (`process.stdin`, `process.stdout` and `process.nextTick`) happen in `readable-stream`. Is it possible to get rid of those dependencies?

**Comment by Jack-Works** [comment]
webpack 5 (released in 2020) no longer provides polyfill for `process` (see https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advice)

I currently replaces `process.stdin` (and `stdout`) to `null`, and `process.nextTick` to a polyfill, but I want to avoid this, since this package is only used in browser, so there is no meaning to use a Node.js global.

**Comment by c1im4cu5** [comment]
I came upon the issue yesterday. Compiling webpack was successful. Upon utilzation of the extenstion, the above error began to appear.

`process` isn't native to the browser. My work-around to the problem was to perform the following steps.

Import and save process to environment:
`npm install process -save`

Modify your webpack configuration to include the 'process' polyfill:

`  plugins: [
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }),
  ],
  resolve: {
    fallback: {
      "process": require.resolve("process/browser"),
    },
  },`

Import to designated file:
`import process from 'process';`

I hope this helps!
